#!/bin/bash

#
# This script is responsible to clean up local repository.
# If you work hard, your local repository will contain hundreds of branches
# which does not exist in the remote repo.

# Useage:
#    prune-all

# Installation:
# Put this file to some place then and chmod +x /path/to/script
# If yoo want to have a git alias for it, you can run the following command:
# set +H && git config --global alias.prune-all "!f(){ ~/path/to/script/prune-all $1; }; f" && set -H

git fetch --prune
git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -D
