#!/bin/sh

#
# This script is responsible to simplify review request workflow
# It creates a PR by using data from git.
#
# Useage:
#    review [issueId] [baseBranch]
#
# Installation:
# Put this file to some place then and chmod +x /path/to/script
# If yoo want to have a git alias for it, you can run the following command:
# set +H && git config --global alias.review "!f(){ ~/path/to/script/review $1; }; f" && set -H
#

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $DIR/common

NEWLINE=$'\n'
BASE_BRANCH=${2-"$R2D2_BASE_BRANCH"}

sayHello

saySmth 'Let me check the state of your work first.'

is_on_valid_branch
logOperation 'Branch is valid.'
saySmth 'OK. Everything is fine. We can proceed.'

saySmth 'I am pushing changes to remote branch.'
git push origin

git_branch="$(git branch | sed -n '/^\*/s/^\* //p')"
git_log=$(git log ${git_branch} --not ${BASE_BRANCH} --pretty="tformat:* %s%n%b")
titles=$(git log -1 --pretty="%s")

if [[ "${#distro[@]}" > 1 ]]; then
    askSmth "Title? " title
else
    title="${titles[0]}"
fi

logOperation 'Gathering changes.'

template="${R2D2_REVIEW_TEMPLATE/"$R2D2_REVIEW_TEMPLATE_GIT_LOG"/$git_log}"
template="${template/"$R2D2_REVIEW_TEMPLATE_BRANCH"/$git_branch}"

if [[ "${R2D2_VERSION_CONTROL:u}" == "github" ]]; then
    logOperation "Looking for existing pull requests in GitHub for head branch ${git_branch}..."
    reviewsInProgres="$(gh pr list --head $git_branch)"

    if [[ ! "${reviewsInProgres}" == *"${git_branch}"* ]]; then
        logOperation 'No reviews found.'

        trap 'rm /tmp/git-review$$' exit; echo "$template" >> /tmp/git-review$$; vim /tmp/git-review$$ >/dev/tty; content=$(cat /tmp/git-review$$)
        gh pr create --title="$title" --base="${BASE_BRANCH}" --body="$content"
        exit
    else
        logOperation "Found reviews:"
        logOperation "$reviewsInProgres"
        saySmth "There is an open PR that matches branch ${git_branch}."
    fi

    sayAllSet
    exit
fi

saySmth 'It looks like you are using not supported Version Control. Only github is supported.'
exit
